name: CI

on:
  workflow_dispatch:

concurrency:
  group: "build"
  cancel-in-progress: true

jobs:

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - run: git clone https://gitlab.lapstime.fr/LapsTime/f1mv-integration-store.git

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Setup pnpm
        # You may pin to the exact commit or the version.
        # uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd
        uses: pnpm/action-setup@v2.2.4
        with:
          # Version of pnpm to install
          version: 7.21.0

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build/release Electron app linux/x64
        run: pnpm build
        env:
          GH_TOKEN: ${{ secrets.TOKEN_GH_RELEASE }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: build
          path: |
            release/**/*.AppImage
  build-windows:
    runs-on: windows-latest

    steps:
      - run: git clone https://gitlab.lapstime.fr/LapsTime/f1mv-integration-store.git

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Setup pnpm
        # You may pin to the exact commit or the version.
        # uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd
        uses: pnpm/action-setup@v2.2.4
        with:
          # Version of pnpm to install
          version: 7.21.0

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build/release Electron app win32/x64
        run: pnpm build
        env:
          GH_TOKEN: ${{ secrets.TOKEN_GH_RELEASE }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: build
          path: |
            release/**/*.exe
  build-macos:
    runs-on: macos-12

    steps:
      - run: git clone https://gitlab.lapstime.fr/LapsTime/f1mv-integration-store.git

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Setup pnpm
        # You may pin to the exact commit or the version.
        # uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd
        uses: pnpm/action-setup@v2.2.4
        with:
          # Version of pnpm to install
          version: 7.21.0

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - run: pnpm add dmg-builder dmg-license

      - name: Build/release Electron app darwin/universal
        run: pnpm build
        env:
          GH_TOKEN: ${{ secrets.TOKEN_GH_RELEASE }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: build
          path: |
            release/**/*.dmg
